"""Authentication & Session V1 routes: login, logout, session context (see ADR 0019).

Every response here sets `Cache-Control: no-store` (a session context, or the fact that a login
attempt happened at all, must never be cached by an intermediary or the browser's own cache).
"""

from fastapi import APIRouter, Depends, Request, Response
from sqlalchemy.orm import Session

from app.api.v1.auth.context import build_session_context
from app.api.v1.auth.deps import get_current_auth_session
from app.api.v1.auth.schemas import LoginRequest, SessionContextResponse
from app.core.auth import SESSION_COOKIE_NAME, clear_session_cookie, set_session_cookie
from app.core.clock import Clock, get_clock
from app.core.config import Settings, get_request_settings
from app.core.exceptions import NotFoundError
from app.db.session import get_session
from app.modules.auth.models import AuthSession
from app.modules.auth.service import AuthService
from app.modules.identity.repository import UserRepository

router = APIRouter(prefix="/auth", tags=["auth"])


@router.post("/login", response_model=SessionContextResponse, summary="Login")
def login(
    payload: LoginRequest,
    request: Request,
    response: Response,
    session: Session = Depends(get_session),
    clock: Clock = Depends(get_clock),
    settings: Settings = Depends(get_request_settings),
) -> SessionContextResponse:
    response.headers["Cache-Control"] = "no-store"
    auth_service = AuthService(session, clock=clock)
    authenticated = auth_service.login(payload.email, payload.password)

    # Session-fixation hygiene: revoke whatever session the incoming cookie names (if any) - the
    # new session's own token is ALWAYS freshly generated by `login()` above, never the incoming
    # value, so this is defence in depth, not what actually prevents fixation.
    incoming_token = request.cookies.get(SESSION_COOKIE_NAME)
    if incoming_token is not None:
        auth_service.logout_by_raw_token(incoming_token)

    set_session_cookie(response, authenticated.raw_token, settings)
    return build_session_context(session, authenticated.user, authenticated.session.expires_at)


@router.post("/logout", status_code=204, response_class=Response, summary="Logout")
def logout(
    request: Request,
    response: Response,
    session: Session = Depends(get_session),
    clock: Clock = Depends(get_clock),
    settings: Settings = Depends(get_request_settings),
) -> Response:
    response.headers["Cache-Control"] = "no-store"
    raw_token = request.cookies.get(SESSION_COOKIE_NAME)
    if raw_token is not None:
        AuthService(session, clock=clock).logout_by_raw_token(raw_token)
    clear_session_cookie(response, settings)
    # Return the SAME (injected) `response` the cookie/header were set on - a freshly constructed
    # `Response(...)` here would silently discard both (FastAPI uses whatever the route function
    # itself returns; the injected `response` is only a convenience for setting things on IT).
    response.status_code = 204
    return response


@router.get("/session", response_model=SessionContextResponse, summary="Session context")
def get_session_context(
    response: Response,
    auth_session: AuthSession = Depends(get_current_auth_session),
    session: Session = Depends(get_session),
) -> SessionContextResponse:
    response.headers["Cache-Control"] = "no-store"
    user = UserRepository(session).get(auth_session.user_id)
    if user is None:  # pragma: no cover - get_current_auth_session already required an active user
        raise NotFoundError("User")
    return build_session_context(session, user, auth_session.expires_at)


__all__ = ["router"]
