"""Small column mixins shared by the ORM models (no hierarchy, no behaviour)."""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, Uuid, func, text
from sqlalchemy.orm import Mapped, mapped_column


class UUIDPrimaryKeyMixin:
    """UUID v4 primary key, generated by the application or, for raw inserts, by PostgreSQL."""

    id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),  # built into PostgreSQL 13+, no extension
    )


class CreatedAtMixin:
    """Server-side creation time (timestamptz: an absolute instant, rendered in UTC)."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )


class TimestampMixin(CreatedAtMixin):
    """created_at + updated_at. updated_at is bumped by the ORM on UPDATE (no trigger)."""

    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now(), onupdate=func.now()
    )
