"""Gate 1: canonical data model and multi-tenant core.

Creates users, workspaces, workspace_memberships, properties, data_sources, import_jobs and
import_files. Written by hand (not autogenerated) so every constraint is deliberate; the model
tests assert that the ORM metadata and this migration stay in sync.

Tenant integrity is enforced by the database with composite foreign keys that carry
workspace_id (see docs/architecture/adr/0006-tenant-integrity.md):

    data_sources (workspace_id, property_id)
        -> properties (workspace_id, id)
    import_jobs (workspace_id, property_id, data_source_id)
        -> data_sources (workspace_id, property_id, id)
    import_files (workspace_id, import_job_id)
        -> import_jobs (workspace_id, id)

Delete policy: only workspace_memberships cascade; every other foreign key is RESTRICT.

Revision ID: 0003_canonical_data_model
Revises: 0002_procrastinate_schema
Create Date: 2026-09-21
"""

from collections.abc import Sequence
from typing import Any

import sqlalchemy as sa
from alembic import op

revision: str = "0003_canonical_data_model"
down_revision: str | None = "0002_procrastinate_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _id() -> sa.Column[Any]:
    return sa.Column("id", sa.Uuid(), nullable=False, server_default=sa.text("gen_random_uuid()"))


def _created_at() -> sa.Column[Any]:
    return sa.Column(
        "created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
    )


def _updated_at() -> sa.Column[Any]:
    return sa.Column(
        "updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")
    )


def _is_active() -> sa.Column[Any]:
    return sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.text("true"))


_SLUG_CHECK = r"slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$' AND char_length(slug) BETWEEN 2 AND 63"


def upgrade() -> None:
    # --- users -------------------------------------------------------------------------------
    op.create_table(
        "users",
        _id(),
        sa.Column("email", sa.String(254), nullable=False),
        sa.Column("display_name", sa.String(200), nullable=True),
        _is_active(),
        _created_at(),
        _updated_at(),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
        sa.CheckConstraint("email = lower(btrim(email))", name=op.f("ck_users_email_normalized")),
        sa.CheckConstraint(
            r"email ~ '^[^@\s]+@[^@\s]+\.[^@\s]+$'", name=op.f("ck_users_email_format")
        ),
        sa.CheckConstraint(
            "display_name IS NULL OR btrim(display_name) <> ''",
            name=op.f("ck_users_display_name_not_blank"),
        ),
    )

    # --- workspaces --------------------------------------------------------------------------
    op.create_table(
        "workspaces",
        _id(),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("slug", sa.String(63), nullable=False),
        _is_active(),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        _created_at(),
        _updated_at(),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspaces")),
        sa.UniqueConstraint("slug", name=op.f("uq_workspaces_slug")),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_workspaces_name_not_blank")),
        sa.CheckConstraint(_SLUG_CHECK, name=op.f("ck_workspaces_slug_format")),
        sa.CheckConstraint(
            "archived_at IS NULL OR NOT is_active",
            name=op.f("ck_workspaces_archived_implies_inactive"),
        ),
    )

    # --- workspace_memberships ---------------------------------------------------------------
    op.create_table(
        "workspace_memberships",
        _id(),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role", sa.String(16), nullable=False),
        _created_at(),
        _updated_at(),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_memberships")),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workspace_memberships_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_workspace_memberships_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.UniqueConstraint(
            "workspace_id", "user_id", name=op.f("uq_workspace_memberships_workspace_id_user_id")
        ),
        sa.CheckConstraint(
            "role IN ('OWNER', 'ADMIN', 'MEMBER')", name=op.f("ck_workspace_memberships_role_valid")
        ),
    )
    op.create_index(op.f("ix_workspace_memberships_user_id"), "workspace_memberships", ["user_id"])

    # --- properties --------------------------------------------------------------------------
    op.create_table(
        "properties",
        _id(),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("slug", sa.String(63), nullable=False),
        sa.Column(
            "timezone", sa.String(64), nullable=False, server_default=sa.text("'Europe/Rome'")
        ),
        sa.Column("currency", sa.String(3), nullable=False, server_default=sa.text("'EUR'")),
        _is_active(),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        _created_at(),
        _updated_at(),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_properties")),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_properties_workspace_id_workspaces"),
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint("workspace_id", "slug", name=op.f("uq_properties_workspace_id_slug")),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_properties_workspace_id_id")),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_properties_name_not_blank")),
        sa.CheckConstraint(_SLUG_CHECK, name=op.f("ck_properties_slug_format")),
        sa.CheckConstraint("btrim(timezone) <> ''", name=op.f("ck_properties_timezone_not_blank")),
        sa.CheckConstraint("currency ~ '^[A-Z]{3}$'", name=op.f("ck_properties_currency_format")),
        sa.CheckConstraint(
            "archived_at IS NULL OR NOT is_active",
            name=op.f("ck_properties_archived_implies_inactive"),
        ),
    )

    # --- data_sources ------------------------------------------------------------------------
    op.create_table(
        "data_sources",
        _id(),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(200), nullable=False),
        sa.Column("domain", sa.String(16), nullable=False),
        sa.Column("source_type", sa.String(32), nullable=False),
        _is_active(),
        _created_at(),
        _updated_at(),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_data_sources")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "property_id"],
            ["properties.workspace_id", "properties.id"],
            name=op.f("fk_data_sources_workspace_id_properties"),
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint(
            "workspace_id",
            "property_id",
            "id",
            name=op.f("uq_data_sources_workspace_id_property_id_id"),
        ),
        sa.CheckConstraint("btrim(name) <> ''", name=op.f("ck_data_sources_name_not_blank")),
        sa.CheckConstraint(
            "domain IN ('BOOKINGS', 'COSTS', 'LABOR')", name=op.f("ck_data_sources_domain_valid")
        ),
        sa.CheckConstraint(
            "source_type IN ('FILE_UPLOAD')", name=op.f("ck_data_sources_source_type_valid")
        ),
    )

    # --- import_jobs -------------------------------------------------------------------------
    op.create_table(
        "import_jobs",
        _id(),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("property_id", sa.Uuid(), nullable=False),
        sa.Column("data_source_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(16), nullable=False, server_default=sa.text("'PENDING'")),
        _created_at(),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error_code", sa.String(100), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_jobs")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "property_id", "data_source_id"],
            ["data_sources.workspace_id", "data_sources.property_id", "data_sources.id"],
            name=op.f("fk_import_jobs_workspace_id_data_sources"),
            ondelete="RESTRICT",
        ),
        sa.UniqueConstraint("workspace_id", "id", name=op.f("uq_import_jobs_workspace_id_id")),
        sa.CheckConstraint(
            "status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED')",
            name=op.f("ck_import_jobs_status_valid"),
        ),
        sa.CheckConstraint(
            "(status = 'PENDING' AND started_at IS NULL AND finished_at IS NULL)"
            " OR (status = 'RUNNING' AND started_at IS NOT NULL AND finished_at IS NULL)"
            " OR (status IN ('SUCCEEDED', 'FAILED') AND finished_at IS NOT NULL)",
            name=op.f("ck_import_jobs_lifecycle_consistent"),
        ),
        sa.CheckConstraint(
            "started_at IS NULL OR finished_at IS NULL OR finished_at >= started_at",
            name=op.f("ck_import_jobs_finished_after_started"),
        ),
        sa.CheckConstraint(
            "(error_code IS NULL AND error_message IS NULL) OR status = 'FAILED'",
            name=op.f("ck_import_jobs_error_only_when_failed"),
        ),
    )
    op.create_index(
        op.f("ix_import_jobs_workspace_id_status"), "import_jobs", ["workspace_id", "status"]
    )

    # --- import_files ------------------------------------------------------------------------
    op.create_table(
        "import_files",
        _id(),
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("import_job_id", sa.Uuid(), nullable=False),
        sa.Column("original_filename", sa.String(255), nullable=False),
        sa.Column("mime_type", sa.String(255), nullable=True),
        sa.Column("size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("sha256", sa.String(64), nullable=True),
        sa.Column("storage_key", sa.String(1024), nullable=True),
        _created_at(),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_import_files")),
        sa.ForeignKeyConstraint(
            ["workspace_id", "import_job_id"],
            ["import_jobs.workspace_id", "import_jobs.id"],
            name=op.f("fk_import_files_workspace_id_import_jobs"),
            ondelete="RESTRICT",
        ),
        sa.CheckConstraint(
            "btrim(original_filename) <> ''",
            name=op.f("ck_import_files_original_filename_not_blank"),
        ),
        sa.CheckConstraint(
            "size_bytes IS NULL OR size_bytes >= 0",
            name=op.f("ck_import_files_size_bytes_non_negative"),
        ),
        sa.CheckConstraint(
            "sha256 IS NULL OR sha256 ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_import_files_sha256_format"),
        ),
    )
    op.create_index(
        op.f("ix_import_files_workspace_id_import_job_id"),
        "import_files",
        ["workspace_id", "import_job_id"],
    )
    op.create_index(
        op.f("ix_import_files_workspace_id_sha256"),
        "import_files",
        ["workspace_id", "sha256"],
        postgresql_where=sa.text("sha256 IS NOT NULL"),
    )


def downgrade() -> None:
    # Children first. Gate 0 objects (Procrastinate) are untouched.
    op.drop_table("import_files")
    op.drop_table("import_jobs")
    op.drop_table("data_sources")
    op.drop_table("properties")
    op.drop_table("workspace_memberships")
    op.drop_table("workspaces")
    op.drop_table("users")
