"""HomeDataService: the safe, read-only SEMANTIC data layer behind Mia Home (Mia V2).

    QuestionResolution  ->  deterministic facts (sections)  ->  OperationalContext

A hotel owner asks "Gli OTA sono a posto?" or "Qual è l'occupazione dei prossimi 7 giorni?". The
answer needs numbers the Decision Feed does not carry (the OTA share when no decision fired, the
occupancy of next week). This service is where they come from - and the ONLY place:

- **Never the model.** No SQL is generated by the model, no table is exposed to it, no arbitrary
  internal API is callable by it. Every figure here is read from a stored snapshot, from an existing
  detector service (`OtaDependencyService`, read-only) or is a plain sum/ratio computed below.
- **No raw records leave this module.** What is returned are small labelled sections ("Occupazione
  sulle prenotazioni attuali: 62,50 %"), never booking rows, guest data, ids or SQL.
- **No new business definition.** Only metrics the repository already defines: `BookingSnapshot`
  (rooms/bookings/revenue/occupancy "on the books"), the OTA dependency evaluation and its channel
  rules (Gate 9). What is NOT defined (fatturato, RevPAR, cancellations, cost/labour figures when no
  decision fired, ...) is reported as "not available" - see `home_facts.UNSUPPORTED_NOTES`.
- **Scoped.** Every query goes through the repositories of the request's `TenantContext` and the
  property resolved by the route; the booking data source is the EXACT one the analysis run recorded
  in its provenance (never guessed, never another property's).
- **The run is the authority.** A decision exists only if the persisted run produced it. Live reads
  (the OTA share) only ADD metrics; they never create, confirm or contradict a decision.

Every section is anchored to the analysis day (`as_of_local_date`): the stored snapshots of that day
describe the nights from the analysis forward ("sulle prenotazioni attuali"), which is exactly how
the answer must be worded - it is not a forecast and not the final occupancy.
"""

import logging
from collections.abc import Callable, Sequence
from dataclasses import dataclass
from datetime import date, timedelta
from decimal import ROUND_HALF_UP, Decimal
from uuid import UUID
from zoneinfo import ZoneInfo

from sqlalchemy.orm import Session

from app.core.tenant import TenantContext
from app.modules.ai.ask_ninfa.home_context_builder import (
    COVERAGE_REF_OF_DOMAIN,
    DOMAIN_OF_DECISION_TYPE,
)
from app.modules.ai.ask_ninfa.home_facts import (
    INTENT_LABELS,
    SUPPORTED_TOPICS,
    UNSUPPORTED_NOTES,
    OperationalContext,
    OperationalSection,
    Row,
)
from app.modules.ai.ask_ninfa.home_intents import QuestionResolution
from app.modules.ai.ask_ninfa.home_period import (
    ResolvedPeriod,
    default_periods,
    italian_day,
    italian_weekday_day,
)
from app.modules.ai.ask_ninfa.home_vocabulary import HomeIntent
from app.modules.ai.ask_ninfa.types import AskDataPoint
from app.modules.bookings.models import BookingChannel
from app.modules.bookings.repository import BookingChannelRepository
from app.modules.decision_memory.types import FeedResult, FeedState
from app.modules.decisions.coverage import (
    AnalysisCoverage,
    AnalysisDomain,
    DomainCoverageStatus,
)
from app.modules.decisions.models import DecisionRun
from app.modules.decisions.provenance import RunInputProvenance
from app.modules.intelligence.distribution.channels import ChannelRow, classify_channels
from app.modules.intelligence.distribution.repository import DistributionRepository
from app.modules.intelligence.distribution.service import OtaDependencyService
from app.modules.intelligence.distribution.temporal import (
    BookingCertainty,
    booking_certainty_at,
    stay_night_overlap,
)
from app.modules.intelligence.distribution.types import (
    FORWARD_STAY_WINDOW_DAYS,
    ChannelGroup,
    EvaluationStatus,
    OtaDependencyEvaluation,
    ReasonCode,
)
from app.modules.intelligence.priority.types import PriorityDecisionType
from app.modules.snapshots.localtime import end_of_local_day
from app.modules.snapshots.models import BookingSnapshot, SnapshotOrigin
from app.modules.snapshots.repository import BookingSnapshotRepository

logger = logging.getLogger(__name__)

OtaEvaluator = Callable[[UUID, UUID, date], OtaDependencyEvaluation]

# A table of one row per night stays readable: beyond this the per-night detail is left out and only
# the aggregate (plus the weakest nights, when asked) is given.
MAX_NIGHT_ROWS = 14
MAX_WEAK_NIGHTS = 5
MAX_CHANNEL_ROWS = 5

_CENT = Decimal("0.01")
_CURRENCY_WORDS = {"EUR": "euro"}

# The decision types each area's outcome is about (what "no decision in this area" refers to).
_AREA_DECISION_TYPES: dict[AnalysisDomain, tuple[PriorityDecisionType, ...]] = {
    AnalysisDomain.REVENUE: (
        PriorityDecisionType.REV_PICKUP_LOW,
        PriorityDecisionType.REV_OCCUPANCY_RISK,
    ),
    AnalysisDomain.DISTRIBUTION: (PriorityDecisionType.REV_OTA_DEPENDENCY,),
    AnalysisDomain.COSTS: (PriorityDecisionType.COST_CPOR_ANOMALY,),
    AnalysisDomain.LABOR: (PriorityDecisionType.LABOR_OVERSTAFFING,),
}
_AREA_NAMES: dict[AnalysisDomain, str] = {
    AnalysisDomain.REVENUE: "Ricavi",
    AnalysisDomain.DISTRIBUTION: "Distribuzione",
    AnalysisDomain.COSTS: "Costi",
    AnalysisDomain.LABOR: "Personale",
}

# Why the OTA evaluation could not judge (an INSUFFICIENT_DATA outcome), in plain Italian.
_OTA_REASON_PHRASES: dict[ReasonCode, str] = {
    ReasonCode.OTA_NO_ON_BOOKS_DEMAND: "nei prossimi 30 giorni non ci sono prenotazioni",
    ReasonCode.OTA_BOOKING_VOLUME_LOW: (
        "le prenotazioni classificate come OTA o dirette nel periodo sono troppo poche"
    ),
    ReasonCode.OTA_CHANNEL_CLASSIFICATION_COVERAGE_LOW: (
        "troppe prenotazioni sono su canali che NINFA non sa classificare come OTA o diretti"
    ),
    ReasonCode.OTA_SNAPSHOT_WINDOW_INCOMPLETE: (
        "i dati di prenotazione dei prossimi 30 giorni sono incompleti"
    ),
    ReasonCode.OTA_SNAPSHOT_WINDOW_UNCERTAIN: (
        "alcune prenotazioni del periodo hanno uno stato incerto"
    ),
    ReasonCode.OTA_CHANNEL_MIX_RECONCILIATION_FAILED: (
        "la composizione per canale non coincide con le prenotazioni registrate"
    ),
    ReasonCode.OTA_COMPARABLE_SAMPLE_INSUFFICIENT: (
        "mancano periodi storici confrontabili per stabilire il livello atteso"
    ),
    ReasonCode.LOW_CONFIDENCE: "l'affidabilità del confronto è troppo bassa",
}
_GROUP_LABELS: dict[ChannelGroup, str] = {
    ChannelGroup.OTA: "OTA",
    ChannelGroup.DIRECT: "diretto",
    ChannelGroup.OTHER: "altro canale",
    ChannelGroup.UNKNOWN: "non classificato",
}


def _money_or_pct(value: Decimal) -> str:
    return format(value.quantize(_CENT, rounding=ROUND_HALF_UP), "f")


def _currency_word(code: str) -> str:
    return _CURRENCY_WORDS.get(code, code)


def describe_period(period: ResolvedPeriod) -> str:
    """ "domani (sabato 10 ottobre)", "i prossimi 7 giorni (dal 8 al 14 ottobre)"."""
    if period.start == period.end:
        if period.label in {"oggi", "domani", "dopodomani", "ieri"}:
            return f"{period.label} ({italian_weekday_day(period.start)})"
        return period.label
    return f"{period.label} (dal {italian_day(period.start)} al {italian_day(period.end)})"


def forward_window_label(start: date, end: date | None = None) -> str:
    """The forward stay window of the OTA / channel metrics, spelled out so it cannot be read as a
    look-back: "i prossimi 30 giorni, dal 3 settembre al 2 ottobre". `end` defaults to the
    window's own last night."""
    last = end if end is not None else start + timedelta(days=FORWARD_STAY_WINDOW_DAYS - 1)
    return (
        f"i prossimi {FORWARD_STAY_WINDOW_DAYS} giorni, "
        f"dal {italian_day(start)} al {italian_day(last)}"
    )


def _period_ref(kind: str, period: ResolvedPeriod) -> str:
    return f"metric:{kind}:{period.start.isoformat()}:{period.end.isoformat()}"


@dataclass(frozen=True, slots=True)
class _Totals:
    nights_requested: int
    nights_with_data: int
    bookings: int
    rooms_on_books: int
    nights_with_capacity: int
    rooms_on_books_with_capacity: int
    rooms_available: int
    revenue: Decimal


def _totals(rows: Sequence[BookingSnapshot], period: ResolvedPeriod) -> _Totals:
    with_capacity = [
        row for row in rows if row.rooms_available is not None and row.rooms_available > 0
    ]
    return _Totals(
        nights_requested=period.nights,
        nights_with_data=len(rows),
        bookings=sum(row.booking_count_on_books for row in rows),
        rooms_on_books=sum(row.rooms_on_books for row in rows),
        nights_with_capacity=len(with_capacity),
        rooms_on_books_with_capacity=sum(row.rooms_on_books for row in with_capacity),
        rooms_available=sum(row.rooms_available or 0 for row in with_capacity),
        revenue=sum((row.allocated_room_revenue_on_books for row in rows), Decimal(0)),
    )


class HomeDataService:
    """Read-only. Pass any session: this service neither commits nor rolls back, writes nothing and
    reads no clock (`as_of_local_date` is always the explicit business date of the feed)."""

    def __init__(
        self,
        session: Session,
        tenant: TenantContext,
        *,
        ota_evaluator: OtaEvaluator | None = None,
    ) -> None:
        self._session = session
        self._tenant = tenant
        self._snapshots = BookingSnapshotRepository(session, tenant)
        self._distribution = DistributionRepository(session, tenant)
        self._channels = BookingChannelRepository(session, tenant)
        self._evaluate_ota: OtaEvaluator = ota_evaluator or self._live_ota_evaluation

    # --- entry point -----------------------------------------------------------------------------

    def collect(
        self,
        resolution: QuestionResolution,
        feed: FeedResult,
        *,
        property_id: UUID,
        timezone: ZoneInfo,
        currency: str,
    ) -> OperationalContext:
        intents = set(resolution.intents)
        sections: list[OperationalSection] = []
        not_available: list[str] = []

        run = feed.run
        source_id = self._booking_source_id(run)
        coverage = self._coverage(run)

        if intents & {HomeIntent.BOOKINGS, HomeIntent.OCCUPANCY, HomeIntent.REVENUE}:
            sections.append(self._area_section(AnalysisDomain.REVENUE, feed, coverage))
            self._snapshot_sections(
                resolution, intents, feed, source_id, currency, sections, not_available
            )
        if HomeIntent.DISTRIBUTION in intents:
            self._distribution_sections(
                resolution,
                feed,
                coverage,
                source_id,
                property_id,
                timezone,
                sections,
                not_available,
            )
        if HomeIntent.COSTS in intents:
            sections.append(self._area_section(AnalysisDomain.COSTS, feed, coverage))
        if HomeIntent.LABOR in intents:
            sections.append(self._area_section(AnalysisDomain.LABOR, feed, coverage))
        if HomeIntent.COMPARISON in intents:
            sections.append(self._areas_summary(feed, coverage))

        for topic in resolution.unsupported:
            not_available.append(UNSUPPORTED_NOTES[topic])
        if resolution.referential:
            not_available.append(
                "la domanda richiama una conversazione precedente che non è disponibile: serve una "
                "domanda più esplicita"
            )

        known = [INTENT_LABELS[intent] for intent in resolution.intents if intent in INTENT_LABELS]
        # With no analysis for today there is nothing Mia could explain beyond what the request
        # already carries (at most the date of the last completed analysis): the generic list of
        # what NINFA "can explain" would promise decisions, OTA status or coverage that are not
        # there.
        offer_topics = resolution.is_unknown and feed.state is not FeedState.NOT_PROCESSED
        return OperationalContext(
            topics=tuple(known),
            from_previous_question=resolution.inherited,
            sections=tuple(sections),
            not_available=tuple(dict.fromkeys(not_available)),
            supported_topics=SUPPORTED_TOPICS if offer_topics else (),
        )

    # --- shared reads ----------------------------------------------------------------------------

    @staticmethod
    def _booking_source_id(run: DecisionRun | None) -> UUID | None:
        """The booking data source the analysis run itself recorded - never inferred, never taken
        from the request. `None` for no run, a run predating provenance, or an unreadable one."""
        if run is None or run.input_provenance is None:
            return None
        try:
            return RunInputProvenance.from_json(run.input_provenance).bookings.data_source_id
        except (KeyError, ValueError):
            return None

    @staticmethod
    def _coverage(run: DecisionRun | None) -> AnalysisCoverage | None:
        if run is None or run.analysis_coverage is None:
            return None
        try:
            return AnalysisCoverage.from_json(run.analysis_coverage)
        except (KeyError, ValueError):
            return None

    # --- area outcomes (decision present / none / not analysed / not assessable) -----------------

    def _area_outcome(
        self, domain: AnalysisDomain, feed: FeedResult, coverage: AnalysisCoverage | None
    ) -> tuple[str, int, str]:
        """(analysis status, decisions in this area, plain-Italian outcome)."""
        types = _AREA_DECISION_TYPES[domain]
        decisions = sum(1 for item in feed.items if item.decision.decision_type in types)
        run = feed.run
        if run is None:
            return (
                "non disponibile",
                0,
                "l'analisi di oggi non è ancora disponibile: NINFA non può valutare quest'area",
            )
        if coverage is None:
            return (
                "non disponibile",
                decisions,
                "la copertura dell'analisi non è registrata per questa analisi: NINFA non può dire "
                "se quest'area sia stata analizzata",
            )
        status = next(item.status for item in coverage.domains if item.domain is domain)
        if status is DomainCoverageStatus.SKIPPED:
            return (
                "non analizzata",
                decisions,
                "quest'area non è stata analizzata: NINFA non può dire che vada tutto bene",
            )
        if decisions > 0:
            return ("analizzata", decisions, "NINFA ha prodotto almeno una decisione in quest'area")
        if run.insufficient_count > 0:
            return (
                "analizzata",
                0,
                "nessuna decisione in quest'area; alcuni controlli dell'analisi (non attribuibili "
                "a una singola area) non avevano dati sufficienti, quindi non si può escludere "
                "un problema non rilevato",
            )
        return (
            "analizzata",
            0,
            "per quanto analizzato oggi, NINFA non ha prodotto decisioni in quest'area",
        )

    def _area_section(
        self, domain: AnalysisDomain, feed: FeedResult, coverage: AnalysisCoverage | None
    ) -> OperationalSection:
        status, decisions, outcome = self._area_outcome(domain, feed, coverage)
        return OperationalSection(
            ref=COVERAGE_REF_OF_DOMAIN[domain],
            title=f"Stato dell'area {_AREA_NAMES[domain]}",
            period=None,
            data=(
                AskDataPoint(label="Area analizzata oggi", value=status, unit=None),
                AskDataPoint(label="Decisioni in quest'area", value=str(decisions), unit=None),
                AskDataPoint(label="Esito", value=outcome, unit=None),
            ),
        )

    def _areas_summary(
        self, feed: FeedResult, coverage: AnalysisCoverage | None
    ) -> OperationalSection:
        """One row per area: analysed or not, how many decisions - and whether the decision NINFA
        itself placed first belongs to it. NINFA's order decides which area is "more critical"; this
        only reports it."""
        first_domain = (
            DOMAIN_OF_DECISION_TYPE[feed.items[0].decision.decision_type] if feed.items else None
        )
        rows: list[Row] = []
        for domain in AnalysisDomain:
            status, decisions, _ = self._area_outcome(domain, feed, coverage)
            rows.append(
                (
                    ("area", _AREA_NAMES[domain]),
                    ("analizzata oggi", status),
                    ("decisioni", str(decisions)),
                    (
                        "contiene la prima decisione nell'ordine di NINFA",
                        "sì" if domain is first_domain else "no",
                    ),
                )
            )
        return OperationalSection(
            ref="summary:areas",
            title="Riepilogo per area",
            period=None,
            data=(),
            rows=tuple(rows),
            note=(
                "l'area più critica per NINFA è quella della decisione messa per prima nel suo "
                "ordine; non esiste un'altra graduatoria"
            ),
        )

    # --- bookings / occupancy / revenue (stored snapshots) ---------------------------------------

    def _snapshot_sections(
        self,
        resolution: QuestionResolution,
        intents: set[HomeIntent],
        feed: FeedResult,
        source_id: UUID | None,
        currency: str,
        sections: list[OperationalSection],
        not_available: list[str],
    ) -> None:
        as_of = feed.as_of_local_date
        periods = (resolution.period,) if resolution.period is not None else default_periods(as_of)
        if feed.run is None:
            not_available.append(
                "l'analisi di oggi non è ancora disponibile: non ci sono dati di prenotazione per "
                "questa data"
            )
            return
        if source_id is None:
            not_available.append(
                "l'origine dei dati di prenotazione non è registrata per questa analisi"
            )
            return

        first = min(period.start for period in periods)
        last = max(period.end for period in periods)
        rows = self._snapshots.list_for_snapshot_date(
            source_id,
            as_of,
            stay_date_from=first,
            stay_date_to=last,
            origin=SnapshotOrigin.OBSERVED,
        )
        for period in periods:
            in_period = [row for row in rows if period.start <= row.stay_date <= period.end]
            self._period_sections(
                period,
                in_period,
                as_of,
                intents,
                resolution.weak_days,
                currency,
                sections,
                not_available,
            )

    def _period_sections(
        self,
        period: ResolvedPeriod,
        rows: Sequence[BookingSnapshot],
        as_of: date,
        intents: set[HomeIntent],
        weak_days: bool,
        currency: str,
        sections: list[OperationalSection],
        not_available: list[str],
    ) -> None:
        label = describe_period(period)
        if period.start < as_of:
            not_available.append(
                f"per le notti precedenti al {italian_day(as_of)} (data dell'analisi) NINFA non ha "
                f"dati di prenotazione: {label}"
            )
        if not rows:
            not_available.append(f"nessun dato di prenotazione per {label} nell'analisi di oggi")
            return

        totals = _totals(rows, period)
        coverage_point = AskDataPoint(
            label="Notti con dati",
            value=f"{totals.nights_with_data} su {totals.nights_requested}",
            unit=None,
        )
        single_night = period.start == period.end

        if HomeIntent.BOOKINGS in intents:
            data = [coverage_point]
            if single_night:
                data.append(
                    AskDataPoint(
                        label="Prenotazioni attive quella notte",
                        value=str(totals.bookings),
                        unit="prenotazioni",
                    )
                )
                data.append(
                    AskDataPoint(
                        label="Camere prenotate quella notte",
                        value=str(totals.rooms_on_books),
                        unit="camere",
                    )
                )
            else:
                data.append(
                    AskDataPoint(
                        label="Camere-notte prenotate nel periodo",
                        value=str(totals.rooms_on_books),
                        unit="camere-notte",
                    )
                )
            sections.append(
                OperationalSection(
                    ref=_period_ref("bookings", period),
                    title="Prenotazioni sulle prenotazioni attuali",
                    period=label,
                    data=tuple(data),
                    note=(
                        "sono le prenotazioni già registrate alla data dell'analisi: non una "
                        "previsione di quante ne arriveranno"
                    ),
                )
            )

        if HomeIntent.OCCUPANCY in intents:
            if totals.nights_with_capacity == 0 or totals.rooms_available == 0:
                data = [
                    coverage_point,
                    AskDataPoint(
                        label="Occupazione sulle prenotazioni attuali",
                        value="non disponibile: la capienza delle camere non è registrata",
                        unit=None,
                    ),
                ]
            else:
                occupancy = (
                    Decimal(totals.rooms_on_books_with_capacity)
                    * 100
                    / Decimal(totals.rooms_available)
                )
                data = [
                    coverage_point,
                    AskDataPoint(
                        label="Occupazione sulle prenotazioni attuali",
                        value=_money_or_pct(occupancy),
                        unit="%",
                    ),
                    AskDataPoint(
                        label="Camere prenotate (notti con capienza nota)",
                        value=str(totals.rooms_on_books_with_capacity),
                        unit="camere-notte",
                    ),
                    AskDataPoint(
                        label="Camere disponibili (notti con capienza nota)",
                        value=str(totals.rooms_available),
                        unit="camere-notte",
                    ),
                    AskDataPoint(
                        label="Notti con capienza nota",
                        value=f"{totals.nights_with_capacity} su {totals.nights_requested}",
                        unit=None,
                    ),
                ]
            sections.append(
                OperationalSection(
                    ref=_period_ref("occupancy", period),
                    title="Occupazione sulle prenotazioni attuali",
                    period=label,
                    data=tuple(data),
                    note=(
                        "è l'occupazione delle camere GIÀ prenotate alla data dell'analisi, non "
                        "l'occupazione finale né una previsione"
                    ),
                )
            )

        if HomeIntent.REVENUE in intents:
            data = [
                coverage_point,
                AskDataPoint(
                    label="Ricavi camera sulle prenotazioni attuali",
                    value=_money_or_pct(totals.revenue),
                    unit=_currency_word(currency),
                ),
            ]
            if totals.rooms_on_books > 0:
                data.append(
                    AskDataPoint(
                        label="Tariffa media per camera-notte sulle prenotazioni attuali",
                        value=_money_or_pct(totals.revenue / Decimal(totals.rooms_on_books)),
                        unit=_currency_word(currency),
                    )
                )
            sections.append(
                OperationalSection(
                    ref=_period_ref("revenue", period),
                    title="Ricavi camera sulle prenotazioni attuali",
                    period=label,
                    data=tuple(data),
                    note=(
                        "ricavi camera delle sole prenotazioni già registrate alla data "
                        "dell'analisi: non sono fatturato né incassi, e non sono una previsione"
                    ),
                )
            )

        if (
            not single_night
            and len(rows) <= MAX_NIGHT_ROWS
            and intents
            & {
                HomeIntent.BOOKINGS,
                HomeIntent.OCCUPANCY,
            }
        ):
            sections.append(
                OperationalSection(
                    ref=_period_ref("nightly", period),
                    title="Dettaglio per notte",
                    period=label,
                    data=(),
                    rows=tuple(self._night_row(row) for row in rows),
                )
            )
        if weak_days and len(rows) >= 2:
            weakest = self._weakest_nights(rows)
            if weakest:
                sections.append(
                    OperationalSection(
                        ref=_period_ref("weakest-nights", period),
                        title="Notti con l'occupazione più bassa sulle prenotazioni attuali",
                        period=label,
                        data=(),
                        rows=tuple(weakest),
                        note=(
                            "è un ordinamento descrittivo delle notti, non una valutazione di "
                            "NINFA: le valutazioni di NINFA sono le sue decisioni"
                        ),
                    )
                )

    @staticmethod
    def _night_row(row: BookingSnapshot) -> Row:
        occupancy = (
            "non disponibile"
            if row.occupancy_on_books is None
            else _money_or_pct(row.occupancy_on_books)
        )
        available = "non disponibile" if row.rooms_available is None else str(row.rooms_available)
        return (
            ("giorno", italian_weekday_day(row.stay_date)),
            ("camere prenotate", str(row.rooms_on_books)),
            ("camere disponibili", available),
            ("occupazione %", occupancy),
        )

    @staticmethod
    def _weakest_nights(rows: Sequence[BookingSnapshot]) -> list[Row]:
        with_occupancy = [row for row in rows if row.occupancy_on_books is not None]
        ordered = sorted(
            with_occupancy,
            key=lambda row: (row.occupancy_on_books or Decimal(0), row.stay_date),
        )[:MAX_WEAK_NIGHTS]
        return [
            (
                ("giorno", italian_weekday_day(row.stay_date)),
                ("occupazione %", _money_or_pct(row.occupancy_on_books or Decimal(0))),
                ("camere prenotate", str(row.rooms_on_books)),
            )
            for row in ordered
        ]

    # --- distribution (OTA share, channel mix, the "are the OTAs fine?" outcome) -----------------

    def _live_ota_evaluation(
        self, property_id: UUID, source_id: UUID, as_of: date
    ) -> OtaDependencyEvaluation:
        return OtaDependencyService(self._session, self._tenant).evaluate(
            property_id=property_id,
            booking_data_source_id=source_id,
            as_of_local_date=as_of,
        )

    def _distribution_sections(
        self,
        resolution: QuestionResolution,
        feed: FeedResult,
        coverage: AnalysisCoverage | None,
        source_id: UUID | None,
        property_id: UUID,
        timezone: ZoneInfo,
        sections: list[OperationalSection],
        not_available: list[str],
    ) -> None:
        as_of = feed.as_of_local_date
        status, decisions, outcome = self._area_outcome(AnalysisDomain.DISTRIBUTION, feed, coverage)
        evaluated_without_decision = status == "analizzata" and decisions == 0
        metrics: OperationalSection | None = None
        # The channel mix only supports an OTA judgement NINFA actually made: a decision, or a
        # clean evaluation. A skipped / unknown / non-assessable area has no judgement to support.
        judged = status == "analizzata" and decisions > 0

        if evaluated_without_decision:
            if source_id is None:
                outcome = (
                    "l'area è stata analizzata ma l'origine dei dati di prenotazione non è "
                    "registrata: la quota OTA non è calcolabile"
                )
            else:
                evaluation = self._safe_ota_evaluation(property_id, source_id, as_of)
                outcome, metrics = self._ota_outcome(evaluation, as_of)
                judged = evaluation is not None and evaluation.status is EvaluationStatus.CLEAR

        sections.append(
            OperationalSection(
                ref=COVERAGE_REF_OF_DOMAIN[AnalysisDomain.DISTRIBUTION],
                title="Stato dell'area Distribuzione e dipendenza OTA",
                period=None,
                data=(
                    AskDataPoint(label="Area analizzata oggi", value=status, unit=None),
                    AskDataPoint(
                        label="Decisioni sulla dipendenza OTA", value=str(decisions), unit=None
                    ),
                    AskDataPoint(label="Esito", value=outcome, unit=None),
                ),
                note=(
                    "'nessuna criticità' significa solo che oggi non è stata superata la soglia "
                    "decisionale di NINFA: non vuol dire che la distribuzione sia perfetta"
                ),
            )
        )
        if metrics is not None:
            sections.append(metrics)

        # A channel the question names ("Quanto pesa Booking?") is an independent, supported metric
        # of the stored bookings; without one, the mix is read only to back a real OTA judgement.
        names_a_channel = bool(resolution.channels)
        if source_id is not None and feed.run is not None and (judged or names_a_channel):
            mix = self._channel_mix_section(resolution, property_id, source_id, as_of, timezone)
            if mix is not None:
                sections.append(mix)
            elif names_a_channel:
                not_available.append(
                    "nei prossimi 30 giorni non ci sono prenotazioni certe da cui ricavare il peso "
                    "dei canali"
                )

    def _safe_ota_evaluation(
        self, property_id: UUID, source_id: UUID, as_of: date
    ) -> OtaDependencyEvaluation | None:
        try:
            return self._evaluate_ota(property_id, source_id, as_of)
        except (
            Exception
        ) as error:  # a read-only enrichment: degrade to "not available", never a guess
            logger.warning("mia ota metrics unavailable error_type=%s", type(error).__name__)
            return None

    @staticmethod
    def _ota_outcome(
        evaluation: OtaDependencyEvaluation | None, as_of: date
    ) -> tuple[str, OperationalSection | None]:
        if evaluation is None:
            return ("la quota OTA non è al momento calcolabile", None)

        metrics = HomeDataService._ota_metrics_section(evaluation, as_of)
        status = evaluation.status
        if status is EvaluationStatus.CLEAR:
            return (
                "per quanto analizzato oggi, NINFA non rileva una criticità actionable sulla "
                "dipendenza OTA",
                metrics,
            )
        if status is EvaluationStatus.INSUFFICIENT_DATA:
            reasons = [
                _OTA_REASON_PHRASES[code]
                for code in evaluation.reason_codes
                if code in _OTA_REASON_PHRASES
            ]
            detail = f" ({'; '.join(reasons)})" if reasons else ""
            return (
                "l'area è stata analizzata ma i dati non bastavano per giudicare la dipendenza "
                f"OTA{detail}: NINFA non può dire che vada tutto bene",
                metrics,
            )
        if status is EvaluationStatus.SUPPRESSED_LOW_CONFIDENCE:
            return (
                "NINFA ha un valore della quota OTA ma non abbastanza affidabile per dire se ci "
                "sia dipendenza: nessun giudizio",
                metrics,
            )
        if status is EvaluationStatus.NOT_APPLICABLE:
            return ("il controllo sulla dipendenza OTA non è applicabile ai dati di oggi", metrics)
        # TRIGGERED on the data as they are NOW, while the persisted run produced no decision: the
        # bookings changed after the analysis. The run is the authority - nothing is asserted.
        return (
            "i dati di prenotazione sono cambiati dopo l'analisi di oggi: NINFA non presenta "
            "l'esito sulla dipendenza OTA finché non viene rifatta l'analisi",
            None,
        )

    @staticmethod
    def _ota_metrics_section(
        evaluation: OtaDependencyEvaluation, as_of: date
    ) -> OperationalSection | None:
        if evaluation.ota_share_exact is None:
            return None
        data = [
            AskDataPoint(
                label="Quota OTA sul totale OTA + diretto",
                value=_money_or_pct(evaluation.ota_share_exact),
                unit="%",
            )
        ]
        if evaluation.direct_share_exact is not None:
            data.append(
                AskDataPoint(
                    label="Quota diretta sul totale OTA + diretto",
                    value=_money_or_pct(evaluation.direct_share_exact),
                    unit="%",
                )
            )
        if evaluation.expected_ota_share_exact is not None:
            data.append(
                AskDataPoint(
                    label="Quota OTA di riferimento (livello atteso)",
                    value=_money_or_pct(evaluation.expected_ota_share_exact),
                    unit="%",
                )
            )
        data.append(
            AskDataPoint(
                label="Periodo considerato",
                value=forward_window_label(evaluation.window_start, evaluation.window_end),
                unit=None,
            )
        )
        if evaluation.classification_coverage_pct_exact is not None:
            data.append(
                AskDataPoint(
                    label="Prenotazioni su canali classificati",
                    value=_money_or_pct(evaluation.classification_coverage_pct_exact),
                    unit="%",
                )
            )
        return OperationalSection(
            ref=f"metric:ota-share:{as_of.isoformat()}",
            title="Quota OTA osservata",
            period=forward_window_label(evaluation.window_start, evaluation.window_end),
            data=tuple(data),
            note=(
                "la quota è calcolata sulle camere-notte classificate come OTA o dirette "
                "(gli altri canali non sono nel totale)"
            ),
        )

    def _channel_mix_section(
        self,
        resolution: QuestionResolution,
        property_id: UUID,
        source_id: UUID,
        as_of: date,
        timezone: ZoneInfo,
    ) -> OperationalSection | None:
        """Certain room-nights per named channel over the same forward 30 nights the OTA
        evaluation observes - with Gate 3's own booking-certainty rule, never a second one."""
        window_end = as_of + timedelta(days=FORWARD_STAY_WINDOW_DAYS - 1)
        channels = list(self._channels.list_for_property(property_id))
        if not channels:
            return None
        groups = classify_channels(
            [ChannelRow(c.id, c.normalized_name, c.channel_type, c.is_verified) for c in channels]
        )
        stays = self._distribution.list_stays_with_channel(
            property_id, source_id, as_of, window_end
        )
        cutoff = end_of_local_day(as_of, timezone)
        room_nights: dict[UUID, int] = {}
        for stay, channel_id in stays:
            if booking_certainty_at(stay, as_of, cutoff) is not BookingCertainty.CERTAIN:
                continue
            nights = sum(1 for _ in stay_night_overlap(stay, as_of, window_end))
            if nights:
                room_nights[channel_id] = room_nights.get(channel_id, 0) + stay.rooms * nights
        total = sum(room_nights.values())
        if total == 0:
            return None

        by_id = {channel.id: channel for channel in channels}
        ranked = sorted(room_nights.items(), key=lambda item: (-item[1], by_id[item[0]].name))
        rows: list[Row] = []
        for channel_id, nights in ranked[:MAX_CHANNEL_ROWS]:
            rows.append(
                (
                    ("canale", by_id[channel_id].name),
                    ("tipo", _GROUP_LABELS[groups[channel_id].group]),
                    ("camere-notte prenotate", str(nights)),
                    (
                        "quota sul totale delle camere-notte prenotate %",
                        _money_or_pct(Decimal(nights) * 100 / Decimal(total)),
                    ),
                )
            )
        data = [
            AskDataPoint(
                label="Camere-notte prenotate nei prossimi 30 giorni (tutti i canali)",
                value=str(total),
                unit="camere-notte",
            )
        ]
        requested = self._requested_channels(resolution, channels, room_nights, total)
        data.extend(requested)
        return OperationalSection(
            ref=f"metric:channel-mix:{as_of.isoformat()}",
            title="Peso dei canali sulle prenotazioni",
            period=forward_window_label(as_of),
            data=tuple(data),
            rows=tuple(rows),
            note=(
                "la quota qui è sul totale di TUTTI i canali: non coincide con la quota OTA, che è "
                "sul solo totale OTA + diretto"
            ),
        )

    @staticmethod
    def _requested_channels(
        resolution: QuestionResolution,
        channels: Sequence[BookingChannel],
        room_nights: dict[UUID, int],
        total: int,
    ) -> list[AskDataPoint]:
        """For each channel the question names (Booking, Expedia, ...): its weight, or the plain
        fact that no such channel appears in this property's data."""
        points: list[AskDataPoint] = []
        for key in resolution.channels:
            matching = [
                channel
                for channel in channels
                if channel.normalized_name == key or channel.normalized_name.startswith(f"{key} ")
            ]
            if not matching:
                points.append(
                    AskDataPoint(
                        label=f"Canale richiesto: {key}",
                        value="non compare tra i canali di questa struttura",
                        unit=None,
                    )
                )
                continue
            nights = sum(room_nights.get(channel.id, 0) for channel in matching)
            name = matching[0].name
            points.append(
                AskDataPoint(
                    label=f"Peso di {name} sul totale delle camere-notte prenotate",
                    value=_money_or_pct(Decimal(nights) * 100 / Decimal(total)),
                    unit="%",
                )
            )
        return points


__all__ = ["MAX_NIGHT_ROWS", "HomeDataService", "OtaEvaluator", "describe_period"]
